### ISSUE TITLE
Stream ingestion error

### ISSUE THREAD

**Issue by slifty** [tvkitchen/appliances#88]
#### Current Behavior
Saw an mpeg processing error when testing a local implementation:

```
/Users/slifty/Dropbox/Code/NodeJS/tvkitchen/appliances/node_modules/ts-demuxer/dist/index.js:397
    if (mem.getUint8(ptr) !== 0x47) {
            ^

RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at demux_packet (/Users/slifty/Dropbox/Code/NodeJS/tvkitchen/appliances/node_modules/ts-demuxer/dist/index.js:397:13)
    at TSDemuxer.process (/Users/slifty/Dropbox/Code/NodeJS/tvkitchen/appliances/node_modules/ts-demuxer/dist/index.js:473:23)
    at Transform._transform (/Users/slifty/Dropbox/Code/NodeJS/tvkitchen/appliances/packages/core/lib/AbstractVideoIngestionAppliance.js:82:26)
    at Transform._read (_stream_transform.js:191:10)
    at Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:454:12)
    at writeOrBuffer (_stream_writable.js:436:5)
    at Transform.Writable.write (_stream_writable.js:327:11)
    at Socket.ondata (_stream_readable.js:708:22)
error Command failed with exit code 1.
```

**Comment by slifty** [comment]
This is resolved, now that we're using [mpegts-demuxer](https://www.npmjs.com/package/mpegts-demuxer)
